-- MySQL Script generated by MySQL Workbench
-- Mon Jun 25 20:39:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbdavinci
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbdavinci
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbdavinci` DEFAULT CHARACTER SET utf8 ;
USE `dbdavinci` ;

-- -----------------------------------------------------
-- Table `dbdavinci`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`roles` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`roles` (
  `ro_idRol` INT NOT NULL AUTO_INCREMENT,
  `ro_nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ro_idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`grados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`grados` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`grados` (
  `gr_idGrado` INT NOT NULL AUTO_INCREMENT,
  `gr_nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`gr_idGrado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`cursos` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`cursos` (
  `cu_idCurso` INT NOT NULL AUTO_INCREMENT,
  `cu_nombre` VARCHAR(15) NOT NULL,
  `cu_idGradoFK` INT NOT NULL,
  `cu_estado` TINYINT NOT NULL,
  PRIMARY KEY (`cu_idCurso`),
  INDEX `FK_cursos_grados_idx` (`cu_idGradoFK` ASC),
  CONSTRAINT `FK_cursos_grados`
    FOREIGN KEY (`cu_idGradoFK`)
    REFERENCES `dbdavinci`.`grados` (`gr_idGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`tipoDocumento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`tipoDocumento` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`tipoDocumento` (
  `td_idTipoDocumento` INT NOT NULL AUTO_INCREMENT,
  `td_nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`td_idTipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`usuarios` (
  `us_idUsuario` INT NOT NULL AUTO_INCREMENT,
  `us_usuario` VARCHAR(15) NOT NULL,
  `us_password` VARCHAR(15) NOT NULL,
  `us_nombre` VARCHAR(20) NOT NULL,
  `us_apellido` VARCHAR(20) NOT NULL,
  `us_idtipoDocumentoFK` INT NOT NULL,
  `us_numeroDocumento` INT NOT NULL,
  `us_idRolFK` INT NOT NULL,
  `us_idCursoFK` INT NULL,
  `us_estado` INT NOT NULL,
  PRIMARY KEY (`us_idUsuario`),
  INDEX `FK_usuario_tipoDocumento_idx` (`us_idtipoDocumentoFK` ASC),
  INDEX `FK_usuario_Rol_idx` (`us_idRolFK` ASC),
  INDEX `FK_usuario_curso_idx` (`us_idCursoFK` ASC),
  CONSTRAINT `FK_usuario_tipoDocumento`
    FOREIGN KEY (`us_idtipoDocumentoFK`)
    REFERENCES `dbdavinci`.`tipoDocumento` (`td_idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_usuario_rol`
    FOREIGN KEY (`us_idRolFK`)
    REFERENCES `dbdavinci`.`roles` (`ro_idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_usuario_curso`
    FOREIGN KEY (`us_idCursoFK`)
    REFERENCES `dbdavinci`.`cursos` (`cu_idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`materias` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`materias` (
  `ma_idMateria` INT NOT NULL AUTO_INCREMENT,
  `ma_nombre` VARCHAR(15) NOT NULL,
  `ma_intensidad` VARCHAR(15) NOT NULL,
  `ma_docenteAsignadoFK` INT NULL,
  PRIMARY KEY (`ma_idMateria`),
  INDEX `FK_materia_usuario_idx` (`ma_docenteAsignadoFK` ASC),
  CONSTRAINT `FK_materia_usuario`
    FOREIGN KEY (`ma_docenteAsignadoFK`)
    REFERENCES `dbdavinci`.`usuarios` (`us_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`periodos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`periodos` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`periodos` (
  `pe_idPeriodo` INT NOT NULL AUTO_INCREMENT,
  `pe_nombre` VARCHAR(15) NOT NULL,
  `pe_estado` TINYINT NOT NULL,
  PRIMARY KEY (`pe_idPeriodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`notas` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`notas` (
  `no_idNota` INT NOT NULL AUTO_INCREMENT,
  `no_nombre` VARCHAR(4) NOT NULL,
  `no_descripcion` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`no_idNota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`estudiantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`estudiantes` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`estudiantes` (
  `es_idEstudiante` INT NOT NULL AUTO_INCREMENT,
  `es_nombre` VARCHAR(20) NOT NULL,
  `es_apellido` VARCHAR(20) NOT NULL,
  `es_codigo` INT NOT NULL,
  `es_idTipoDocumentoFK` INT NOT NULL,
  `es_numeroDocumento` INT NOT NULL,
  `es_jornada` VARCHAR(10) NOT NULL,
  `es_idRolFK` INT NOT NULL,
  `es_idCursoFK` INT NOT NULL,
  `es_fotoEstudiante` LONGBLOB NOT NULL,
  `es_estado` TINYINT NOT NULL,
  PRIMARY KEY (`es_idEstudiante`),
  INDEX `FK_estudiante_tipoDocumento_idx` (`es_idTipoDocumentoFK` ASC),
  INDEX `FK_estudiante_rol_idx` (`es_idRolFK` ASC),
  INDEX `FK_estudiante_curso_idx` (`es_idCursoFK` ASC),
  CONSTRAINT `FK_estudiante_tipoDocumento`
    FOREIGN KEY (`es_idTipoDocumentoFK`)
    REFERENCES `dbdavinci`.`tipoDocumento` (`td_idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_estudiante_rol`
    FOREIGN KEY (`es_idRolFK`)
    REFERENCES `dbdavinci`.`roles` (`ro_idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_estudiante_curso`
    FOREIGN KEY (`es_idCursoFK`)
    REFERENCES `dbdavinci`.`cursos` (`cu_idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`procesos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`procesos` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`procesos` (
  `pro_idProceso` INT NOT NULL AUTO_INCREMENT,
  `pro_nombre` VARCHAR(30) NOT NULL,
  `pro_idMateriaFK` INT NOT NULL,
  `pro_idPeriodoFK` INT NOT NULL,
  `pro_idGradoFK` INT NOT NULL,
  PRIMARY KEY (`pro_idProceso`),
  INDEX `FK_proceso_materia_idx` (`pro_idMateriaFK` ASC),
  INDEX `FK_proceso_periodo_idx` (`pro_idPeriodoFK` ASC),
  INDEX `FK_proceso_grado_idx` (`pro_idGradoFK` ASC),
  CONSTRAINT `FK_proceso_materia`
    FOREIGN KEY (`pro_idMateriaFK`)
    REFERENCES `dbdavinci`.`materias` (`ma_idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_proceso_periodo`
    FOREIGN KEY (`pro_idPeriodoFK`)
    REFERENCES `dbdavinci`.`periodos` (`pe_idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_proceso_grado`
    FOREIGN KEY (`pro_idGradoFK`)
    REFERENCES `dbdavinci`.`grados` (`gr_idGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`competencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`competencias` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`competencias` (
  `co_idCompetencia` INT NOT NULL AUTO_INCREMENT,
  `co_nombre` VARCHAR(15) NOT NULL,
  `co_descripción` VARCHAR(50) NOT NULL,
  `co_idProcesoFK` INT NOT NULL,
  `co_estado` TINYINT NOT NULL,
  PRIMARY KEY (`co_idCompetencia`),
  INDEX `FK_competencia_proceso_idx` (`co_idProcesoFK` ASC),
  CONSTRAINT `FK_competencia_proceso`
    FOREIGN KEY (`co_idProcesoFK`)
    REFERENCES `dbdavinci`.`procesos` (`pro_idProceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`tipoObservaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`tipoObservaciones` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`tipoObservaciones` (
  `to_idTipoObservacion` INT NOT NULL AUTO_INCREMENT,
  `to_nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`to_idTipoObservacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`observaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`observaciones` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`observaciones` (
  `ob_idObservaciones` INT NOT NULL AUTO_INCREMENT,
  `ob_idTipoObservacionFK` INT NOT NULL,
  `ob_descripción` VARCHAR(50) NOT NULL,
  `ob_estado` TINYINT NOT NULL,
  PRIMARY KEY (`ob_idObservaciones`),
  INDEX `FK_observaciones_tipoObservaciones_idx` (`ob_idTipoObservacionFK` ASC),
  CONSTRAINT `FK_observaciones_tipoObservaciones`
    FOREIGN KEY (`ob_idTipoObservacionFK`)
    REFERENCES `dbdavinci`.`tipoObservaciones` (`to_idTipoObservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`calificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`calificaciones` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`calificaciones` (
  `ca_idCalificacion` INT NOT NULL AUTO_INCREMENT,
  `ca_anioBoletin` YEAR NOT NULL,
  `ca_nombreEstudianteFK` INT NOT NULL,
  `ca_periodoFK` INT NOT NULL,
  `ca_materiaFK` INT NOT NULL,
  `ca_docenteMateriaFK` INT NOT NULL,
  `ca_fallasMateria` INT NOT NULL,
  `ca_procesoMateria` INT NOT NULL,
  `ca_Competencia` INT NOT NULL,
  `ca_notaCompetencia` INT NOT NULL,
  PRIMARY KEY (`ca_idCalificacion`),
  INDEX `FK_boletin_estudiante_idx` (`ca_nombreEstudianteFK` ASC),
  INDEX `FK_boletin_periodo_idx` (`ca_periodoFK` ASC),
  INDEX `FK_boletin_proceso_idx` (`ca_procesoMateria` ASC),
  INDEX `FK_boletin_Materia_idx` (`ca_docenteMateriaFK` ASC),
  INDEX `FK_boletin_notaCompetencia1_idx` (`ca_notaCompetencia` ASC),
  INDEX `FK_boletin_Competencia1_idx` (`ca_Competencia` ASC),
  INDEX `FK_boletin_materiaProceso_idx` (`ca_materiaFK` ASC),
  CONSTRAINT `FK_boletin_estudiante`
    FOREIGN KEY (`ca_nombreEstudianteFK`)
    REFERENCES `dbdavinci`.`estudiantes` (`es_idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_boletin_periodo`
    FOREIGN KEY (`ca_periodoFK`)
    REFERENCES `dbdavinci`.`periodos` (`pe_idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_boletin_docente`
    FOREIGN KEY (`ca_docenteMateriaFK`)
    REFERENCES `dbdavinci`.`materias` (`ma_docenteAsignadoFK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_boletin_proceso`
    FOREIGN KEY (`ca_procesoMateria`)
    REFERENCES `dbdavinci`.`procesos` (`pro_idProceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_boletin_materiaProceso`
    FOREIGN KEY (`ca_materiaFK`)
    REFERENCES `dbdavinci`.`procesos` (`pro_idMateriaFK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_boletin_notaCompetencia1`
    FOREIGN KEY (`ca_notaCompetencia`)
    REFERENCES `dbdavinci`.`notas` (`no_idNota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_boletin_Competencia1`
    FOREIGN KEY (`ca_Competencia`)
    REFERENCES `dbdavinci`.`competencias` (`co_idCompetencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdavinci`.`boletines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdavinci`.`boletines` ;

CREATE TABLE IF NOT EXISTS `dbdavinci`.`boletines` (
  `bo_idBoletin` INT NOT NULL AUTO_INCREMENT,
  `bo_nombreEstudiante` INT NOT NULL,
  `bo_fortalezasFK` INT NOT NULL,
  `bo_debildadesFK` INT NULL,
  PRIMARY KEY (`bo_idBoletin`),
  INDEX `FK_boletines_observaciones_idx` (`bo_fortalezasFK` ASC),
  INDEX `FK_boletines_estudiante_idx` (`bo_nombreEstudiante` ASC),
  CONSTRAINT `FK_boletines_observaciones`
    FOREIGN KEY (`bo_fortalezasFK`)
    REFERENCES `dbdavinci`.`observaciones` (`ob_idObservaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_boletines_estudiante`
    FOREIGN KEY (`bo_nombreEstudiante`)
    REFERENCES `dbdavinci`.`estudiantes` (`es_idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
